apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: worldcoin/bedrock
  tags: ['code-lang:rust']
  description: Foundational library which powers World App's crypto wallet.
  links:
    - title: Documentation
      url: https://docs.toolsforhumanity.com/world-app/bedrock
  name: bedrock # GitHub slug
spec:
  lifecycle: production
  owner: app # https://github.com/orgs/worldcoin/teams
  type: library # https://backstage.io/docs/features/software-catalog/system-model/