[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install pkg-config:$CROSS_DEB_ARCH",
    "export PKG_CONFIG_ALLOW_CROSS=1",
    "export PKG_CONFIG_LIBDIR=/usr/lib/$CROSS_DEB_ARCH/pkgconfig:/usr/lib/$CROSS_DEB_ARCH/lib/pkgconfig:/usr/share/pkgconfig",
]

# max-page-size=16384: 
# Android 15 (API 35) introduces support for 16KB page sizes to improve performance on devices with larger RAM.
# Apps with native libraries MUST be compiled with 16KB ELF alignment or they will crash on startup
# on devices configured with 16KB page sizes. This flag ensures proper alignment for both 32-bit and 64-bit targets.
# Reference: https://developer.android.com/guide/practices/page-sizes
[build.env]
RUSTFLAGS = "-C link-arg=-Wl,-z,max-page-size=16384"
