# Configuration for direct cargo builds (without cross)

# max-page-size=16384: 
# Android 15 (API 35) introduces support for 16KB page sizes to improve performance on devices with larger RAM.
# Apps with native libraries MUST be compiled with 16KB ELF alignment or they will crash on startup
# on devices configured with 16KB page sizes. This flag ensures proper alignment for both 32-bit and 64-bit targets.
# Reference: https://developer.android.com/guide/practices/page-sizes
[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]
